# author: Arshia Z. Hassan. hassa418@umn.edu

local_R_path = "../../local/R/library/"
library("stringi", local_R_path)
library("stringr", local_R_path)
library("rstudioapi", local_R_path)
library("desc", local_R_path)
library("withr", local_R_path)
library("ps", local_R_path)
library("usethis", local_R_path)
library("devtools", local_R_path)
library("RColorBrewer", local_R_path)
library("tibble", local_R_path)


input_folder<-'./'

# load mitochondrial gene list
mito_gene_list_file_genes <- "./Mitochondial_genelist_1_26_2021_genes.tsv"
mito_data_genes <- read.csv(mito_gene_list_file_genes, sep = " ", header = F, stringsAsFactors = F)

# load suppressor information file (generated by generate_all_significant_positive_GIs_suppression_metric.R)
supp_data = read.csv("./data/all_tested_GIs_with_supp_score_metric_2_.9.csv",header=T,sep=',')
supp_pairs = data.frame(supp_data[,c("library_gene","query_gene","score")])

# load flex package
flex_folder <- "./FLEX_R-master"
load_all(flex_folder)
pathway_std <- MakeCoAnnotationFromGeneSymbols(data_standard = data_pathway, overlap_length = 1,file_location = "pathway")

# generate and store Precision-Recall data based on suppression score wrt to pathway standard 
pathway <- FromGenePairSimilarity(pathway_std, supp_pairs)
save(pathway,file=file.path(input_folder, "suppressors_all_pairs_PW_metric_2_.9.Rdata"))

# remove mitochondrial gene pairs and store Precision-Recall data
pathway_no_mito <- getSubsetOfCoAnnRemovePairs(pathway_std, data.frame(pathway), list(mito_data_genes$V1), replace = F)
save(pathway_no_mito,file=file.path(input_folder, "suppressors_no_mito_PW_metric_2_.9.Rdata"))

