# author: Arshia Z. Hassan. hassa418@umn.edu

options(java.parameters = "- Xmx1024m")
packages <- c("ggplot2", "ggthemes",'ggpubr','rstatix')
for (p in packages) {
  library(p, character.only = TRUE)
}

# Function to generate suppressor AUPRC fold-enrichment barplots
GeneratePRFEbarplot <- function(data, output_folder, file_prefix){
	
	# get baseline precision
	#auprc_baseline = sum(data['TRUE.'])/nrow(data)
	auprc_baseline = data$y[nrow(data)]
	# get precisions at different suppression score cutoffs
	y.8 = data$y[max(which(data$predicted > .8))]
	y.5 = data$y[max(which(data$predicted > .5))]
	y.2 = data$y[max(which(data$predicted > .2))]
	y.0 = data$y[max(which(data$predicted > -1))]

	#calculate precision fold change at different suppression score cutoff
	FE_df = data.frame(x = c('background','S>0.8','S>0.5','S>0.2','pos_GI'), y = c(auprc_baseline/auprc_baseline,y.8/auprc_baseline,y.5/auprc_baseline,y.2/auprc_baseline,y.0/auprc_baseline))

	# prepare data to measure enrichment - proportion test: pairwise fisher exact test
	# count how many positives and negatives are in each suppression score cutoff set and compare the sets using proportion test
	baseline_1 = sum(data$true)
	baseline_0 = nrow(data)-baseline_1
	
	df.8 = data[which(data$predicted > .8),]
	df.8_1 = sum(df.8$true)
	df.8_0 = nrow(df.8)-df.8_1

	df.5 = data[which(data$predicted > .5),]
	df.5_1 = sum(df.5$true)
	df.5_0 = nrow(df.5)-df.5_1

	df.2 = data[which(data$predicted > .2),]
	df.2_1 = sum(df.2$true)
	df.2_0 = nrow(df.2)-df.2_1

	df.0 = data[which(data$predicted > -1),]
	df.0_1 = sum(df.0$true)
	df.0_0 = nrow(df.0)-df.0_1

	xtab <- as.table(rbind(c(baseline_1, baseline_0),
						   c(df.8_1, df.8_0),
						   c(df.5_1, df.5_0),
						   c(df.2_1, df.2_0),
						   c(df.0_1, df.0_0)
						   )
	)

	dimnames(xtab) <- list(
	  group = c('background','S>0.8','S>0.5','S>0.2','pos_GI'),
	  fa = c("yes", "no")
	)

	xtab_df = data.frame(xtab)

	write.csv(xtab_df,file.path(output_folder, paste(file_prefix,'_FE_data.csv',sep='')),row.names = F)

	#stat.test = pairwise_prop_test(xtab, p.adjust.method = "none")
	stat.test_fisher = pairwise_fisher_test(xtab, p.adjust.method = "none",detailed=T)

	write.csv(stat.test_fisher,file.path(output_folder, paste(file_prefix,'_fisher_exact_results.csv',sep='')),row.names = F)

	stat.test_fisher_sub = stat.test_fisher[1:4,]
	stat.test_fisher_sub$y.position = 2.05
	stat.test_fisher_sub$xmin = c(1,1,1,1)
	stat.test_fisher_sub$xmax = c(5,4,3,2)
	#stat.test_fisher_sub <- stat.test_fisher_sub %>%
	  #add_x_position()

	plot1 <- ggplot(FE_df, aes(x=as.factor(x), y=as.numeric(y))) + 
	  geom_bar(stat = "identity")+
	  xlab("") +
	  ylab("FE") +
	  stat_pvalue_manual(
		stat.test_fisher_sub,  label = "{p}", tip.length = 0.1, hide.ns = TRUE, #"{p}{p.adj.signif}"
		step.increase = 0.2, bracket.nudge.y = 0.1, size=10
	  )+
	  theme_bw() +
	  theme(
		#axis.title.x=element_blank(),axis.title.y=element_blank(), axis.text.y = element_blank(),
		axis.text.y = element_text(family="ArialMT",size = 30,colour = "black"),
		legend.title = element_text(family="ArialMT",size = 25,colour = "black"),
		legend.text = element_text(family="ArialMT",size = 25,colour = "black"),
		axis.title = element_text(family="ArialMT",size = 25,colour = "black"),
		panel.border = element_blank(), panel.grid.major = element_blank(), 
		axis.text.x = element_text(family="ArialMT",size = 30,colour = "black",angle = 90, vjust = 0.5),
		panel.grid.minor = element_blank(), axis.line = element_line(colour = "black",size = 1)
	  )+ 
	  scale_y_continuous(expand = expansion(mult = c(0, 0.1)))

	ggsave(file.path(output_folder, paste(file_prefix,'_FE_barplot.pdf',sep='')), device = cairo_pdf,height = 10 , width = 10)

}

# load data generated by generate_PR_data_and_curve.R and produce auprc fold enrichhment barplots
input_folder<-'./'
output_folder = './'
data = read.csv(file.path(input_folder,'all_pairs_PW_PR.csv'))
file_prefix = 'all_pairs_PW_PR'
GeneratePRFEbarplot(data,output_folder,file_prefix)

data = read.csv(file.path(input_folder,'all_pairs_GO_PR.csv'))
file_prefix = 'all_pairs_GO_PR'
GeneratePRFEbarplot(data,output_folder,file_prefix)

data = read.csv(file.path(input_folder,'no_mito_PW_PR.csv'))
file_prefix = 'no_mito_PW_PR'
GeneratePRFEbarplot(data,output_folder,file_prefix)

data = read.csv(file.path(input_folder,'no_mito_GO_PR.csv'))
file_prefix = 'no_mito_GO_PR'
GeneratePRFEbarplot(data,output_folder,file_prefix)