# author: Arshia Z. Hassan. hassa418@umn.edu

local_R_path = "../../../local/R/library/"
library("reshape2", lib.loc=local_R_path)
library("tibble", lib.loc=local_R_path)
library("dplyr", lib.loc=local_R_path)

# load qGI score and FDR data (non-redundant screen set ) and get all tested GIs
data_qGI_nRed <- read.table('./qGI_20211111_nRed.txt', header = TRUE, sep = '\t', stringsAsFactors = FALSE) 
data_fdr_nRed <- read.table('./gi_FDR_20211111_nRed.txt', header = TRUE, sep = '\t', stringsAsFactors = FALSE) 

data_qGI_nRed_melt <- setNames(melt(as.matrix(data_qGI_nRed)), c('library_gene', ' query_name', 'qGI_score'))
data_fdr_nRed_melt <- setNames(melt(as.matrix(data_fdr_nRed)), c('library_gene', ' query_name', 'FDR'))

all_tested_GIs = merge(data_qGI_nRed_melt,data_fdr_nRed_melt,by = c('library_gene', ' query_name'))
colnames(all_tested_GIs) = c("library_gene"," query_name","qGI_score", 'FDR')
#all_tested_GIs$score = -1

# load suppressor information file (generated by generate_all_significant_positive_GIs_suppression_metric.R)
supp_file = "./all_significant_positive_GIs_supp_metric_2_.9_.csv"
supp_data = read.csv(supp_file, stringsAsFactors=FALSE)
supp_data_sub = supp_data[,c("library_gene","X.query_name","qGI_score", "FDR", "query_gene","score")]
colnames(supp_data_sub) = c("library_gene"," query_name","qGI_score", "FDR", "query_gene","score")

# set non-suppressor tested GI score to -1
all_tested_GIs_w_score = merge(all_tested_GIs[,c("library_gene"," query_name")], supp_data_sub[,c("library_gene"," query_name","score")], by=c("library_gene"," query_name"), all.x=TRUE)
sum(!is.na(all_tested_GIs_w_score$score))
all_tested_GIs_w_score$score[is.na(all_tested_GIs_w_score$score)] <- -1
split_screen_name<-function(x)
{
  x1<-strsplit(x,"_")[[1]][1] #split x with delimiter \. and retrieve first sub-string
  return( x1)
}
all_tested_GIs_w_score$query_gene <- unlist(lapply(as.character(all_tested_GIs_w_score$` query_name`),split_screen_name) )

write.csv(all_tested_GIs_w_score,'./all_tested_GIs_with_supp_score_metric_2_.9.csv',row.names = F)


