# author: Arshia Z. Hassan. hassa418@umn.edu

local_R_path = "../../local/R/library/"
library("stringi", local_R_path)
library("stringr", local_R_path)
library("rstudioapi", local_R_path)
library("desc", local_R_path)
library("withr", local_R_path)
library("ps", local_R_path)
library("usethis", local_R_path)
library("devtools", local_R_path)
library("RColorBrewer", local_R_path)
library("tibble", local_R_path)

# load mitochondrial gene list
mito_gene_list_file_genes <- "./data/Mitochondial_genelist_1_26_2021_genes.tsv"
mito_data_genes <- read.csv(mito_gene_list_file_genes, sep = " ", header = F, stringsAsFactors = F)

# load suppressor information file (generated by generate_all_significant_positive_GIs_suppression_metric.R)
supp_data = read.csv("./all_tested_GIs_with_supp_score_metric_2_.9.csv",header=T,sep=',')
supp_pairs = data.frame(supp_data[,c("library_gene","query_gene","score")])

input_folder<-'./'

# load flex package
flex_folder <- "./FLEX_R-master"
load_all(flex_folder)
go_bp <- MakeCoAnnotationFromGeneSymbols(data_standard = data_GO_BP, overlap_length = 1,file_location = "GO")

# generate and store Precision-Recall data based on suppression score wrt to GO-BP standard
go <- FromGenePairSimilarity(go_bp, supp_pairs)
save(go,file=file.path(input_folder, "suppressors_all_pairs_GO_metric_2_.9.Rdata"))
corum_sim <- list(list(true = go$true, predicted = go$predicted))

# remove mitochondrial gene pairs and store Precision-Recall data
go_no_mito <- getSubsetOfCoAnnRemovePairs(go_bp, data.frame(go), list(mito_data_genes$V1), replace = F)
save(go_no_mito,file=file.path(input_folder, "suppressors_no_mito_GO_metric_2_.9.Rdata"))
corum_sim_no_mito <- list(list(true = go_no_mito$true, predicted = go_no_mito$predicted))
